### PR TITLE
Implement the Chi2Test from ROOT

### PR DESCRIPTION
**Pull request by VaiTon**
I've implemented only the WW version, but it should be correct. Sorry for the formatting changes, I can revert them if you'd like me to :)

### CODE REVIEW

**Comment by Moelf** [comment]
Yeah not a fan of formatting.

Also I think we shouldn't have Chi2Test here. There's plenty of them at https://juliastats.org/HypothesisTests.jl/stable/

**Comment by VaiTon** [comment]
@Moelf unfortunately I did not find the exact ROOT implementation in that package, and because I need a "drop-in" kind of substitution I re-implemented it. I can create a new package that tries to mimic the work of ROOT in this regard though :)

**Comment by Moelf** [comment]
that's fair, me personally definitely welcome a new addition to JuliaHEP org where we provide common statistical test and histogram algorithms seen in ROOT and RooFit

**Comment by VaiTon** [comment]
FYI, I've created https://github.com/VaiTon/ROOTStats.jl

**Pull request closed without merging**
