### PR TITLE
Add histodemo.jl notebook

### PR DESCRIPTION
**Pull request by jjgomezcadenas**
A pluto notebook documenting some of the functionality of FHist.

### CODE REVIEW

**Comment by Moelf** [comment]
the trigger of recipe base comes from loading `Plots.jl` so one shouldn't be loading `RecipeBase.jl` unless they have that explicitly installed.

Since it runs now, do you want to clean up it a bit? I want this to mirror the notebook we have for CairoMakie.

Btw, I like the documentation you're doing in this notebook, but they should probably be in the main documentation, if you don't mind I can do the editing

**Comment by jjgomezcadenas** [comment]
Go ahead, do the editing at will. Let me know if you want me to do anything else.

**Comment by Moelf** [comment]
does this look good to you?

**Comment by jjgomezcadenas** [comment]
> does this look good to you?

Looks great

**Pull request merged**
