### PR TITLE
feat: add Makie plot for Hist3D

### PR DESCRIPTION
**Pull request by Beforerr**

### CODE REVIEW

**Comment by Moelf** [comment]
thanks for this! can you add an example in the https://github.com/Moelf/FHist.jl/blob/main/docs/src/notebooks/makie_plotting.jl?

I'm also curious to what this would look like (i.e. is it legible?)

**Comment by Beforerr** [comment]
I am not sure if I could add the example because one have to use GLMakie for now. CairoMakie does not support volume now. The example is straightforward, and the output figure is attached below.

```
using FHist
h3 = Hist3D((x,y,z), nbins=[10,10,10])
fig = Figure()
ax = Axis3(fig[1, 1];  width = 400)
plot!(h3)
fig
```

image

**Comment by Moelf** [comment]
Ok I think looks good enough for me I assume you already find this useful

**Comment by tamasgal** [comment]
Looks wild for sure 😉

**Pull request merged**
