### PR TITLE
[don't look inside] specialize on...nthreads

### PR DESCRIPTION
**Pull request by aminnj**
We have a `lock(h)`/`unlock(h)` in `push!` which just wastes time when the julia instance has 1 thread. Luckily we can change that with only a couple of lines :)

This probably helps everyone who has not aliased `julia` -> `julia -t 4` ;)

### CODE REVIEW

**Comment by Moelf** [comment]
we should ask if this is safe. I have a feeling this is bad practice (at best)...

**Comment by aminnj** [comment]
There's a 99% chance this is bad practice. Let me figure out why, after I restarted my julia session, everything fails. :(

**Comment by Moelf** [comment]
btw, I thought we have decided to make `push!()` unsafe by default after the chat with StatsBase people

**Comment by aminnj** [comment]
Ah right. That would make the default (push) behavior/performance identical to what I'm achieve with this hack...

**Comment by aminnj** [comment]
OK let me fix this hack for fun and I'll make a PR for the smarter change tomorrow

**Comment by aminnj** [comment]
OK, it didn't like the `let` construct. Anyway, as it is now, it won't work because as you suggested to me, it will get precompiled with one of the two options :(.

**Pull request closed without merging**
