### PR TITLE
add docs, add new projection

### PR DESCRIPTION
**Pull request by bojohnson5**
This package/project is awesome, I really like it! I was needing the ability to project only certain slices of a 2D histogram and have added that ability along with a test for it. I started a (maybe) more readable docs page instead of symlinking the readme. Also did some reorganizing of the src code like running it through a formatter and renamed some keyword arguments to all be consistent. Let me know if I can change anything.

### CODE REVIEW

**Comment by Moelf** [comment]
wow amazing, I will have to take a look this weekend, if I don't get back to you soon-ish please pin me again

(I guess Formatter has a bunch of noise, but this good!)

**Comment by Moelf** [comment]
"binedges" renaming is breaking right? we probably need to mention that in Changelog

**Comment by Moelf** [comment]
you can keep pushing to the same branch in your repo and changes will be reflected here

**Comment by Moelf** [comment]
having Formatter.jl changes mixed in this PR is quite noisy, it might be nice to separate formatting into a separate PR, but this is fine it will just take me longer to review

**Comment by bojohnson5** [comment]
Got it, I'll remember that for the future

**Comment by Moelf** [comment]
I might use https://github.com/MilesCranmer/DeprecateKeywords.jl when I have time to fully review this! thanks again

**Comment by bojohnson5** [comment]
Added the DeprecateKeywords dependency and seems to be working.

**Comment by bojohnson5** [comment]
@Moelf let me know if I can change/add anything.

**Comment by Moelf** [comment]
I'm having trouble seeing the deprecated keywords taking effect:
```julia
> julia --project=. --depwarn=yes
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.2 (2023-07-05)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using FHist

julia> Hist1D(Float64; bins=0:0.1:1)
ERROR: UndefKeywordError: keyword argument `binedges` not assigned
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1
```

**Comment by bojohnson5** [comment]
Looks like in order to use `DeprecateKeywords.jl` the keyword argument needs to have a default value provided. Added a simple default but not sure if it's the ideal long term solution. Maybe could look at getting that behavior changed in that package?

**Comment by Moelf** [comment]
yeah I guess having default value is not ideal, let me open an issue there

**Comment by bojohnson5** [comment]
@Moelf let me know if there's anything else I need to add to/change for this pull request.

**Comment by bojohnson5** [comment]
I'm going to restart this pull request, adding the feature but not adding other changes.

**Comment by Moelf** [comment]
sounds good, sorry I couldn't review this in time

**Comment by bojohnson5** [comment]
Yeah I think I tried to do too much at once. Hopefully I can break it out into more manageable PRs soon.

**Pull request closed without merging**
